# Generated by Django 5.1.2 on 2024-11-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('user', 'Usuario'), ('gerente', 'Gerente')], default='user', max_length=20),
        ),
    ]
