# Generated by Django 5.1.2 on 2024-11-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usuario',
            field=models.CharField(default='Usuario', max_length=40),
        ),
    ]
